'use strict';

angular.module('specifyDataCleanerApp')
	.service('Icons', function() {
		// AngularJS will instantiate a singleton by calling "new" on this function
		var that = this;
		this.datamodel = {
			get: function(iconname) {
				console.log(iconname);
				return that.groups.datamodel[iconname.toLowerCase()];
			}
		};

		this.discipline = {
			get: function(iconname) {
				console.log(iconname);
				return that.groups.discipline[iconname.toLowerCase()];
			}
		};

		this.imgproc = {
			get: function(iconname) {
				console.log(iconname);
				return that.groups.imgproc[iconname.toLowerCase()];
			}
		};

		this.plugin = {
			get: function(iconname) {
				console.log(iconname);
				return that.groups.plugin[iconname.toLowerCase()];
			}
		};

		this.
		default = {
			get: function(iconname) {
				console.log(iconname);
				return that.groups.
				default [iconname.toLowerCase()];
			}
		};

		this.groups = {};

		this.groups.datamodel = {
			"colobj_backstop": "assets/images/specify/datamodel/collection_object.png",
			"accession": "assets/images/specify/datamodel/accession.png",
			"deaccession": "assets/images/specify/datamodel/deaccession.png",
			"appraisal": "assets/images/specify/datamodel/appraisal.png",
			"accessionagent": "assets/images/specify/datamodel/agent.png",
			"address": "assets/images/specify/datamodel/address.png",
			"addressofrecord": "assets/images/specify/datamodel/address.png",
			"agent": "assets/images/specify/datamodel/agent.png",
			"agentgeography": "assets/images/specify/datamodel/agent_geography.png",
			"agentspecialty": "assets/images/specify/datamodel/agent_specialty.png",
			"agentvariant": "assets/images/specify/datamodel/agent.png",
			"author": "assets/images/specify/datamodel/author.png",
			"attachment": "assets/images/specify/datamodel/attachment.png",
			"attribute": "assets/images/specify/datamodel/attribute.png",
			"attributedef": "assets/images/specify/datamodel/attribute_def.png",
			"borrow": "assets/images/specify/datamodel/borrow.png",
			"borrowmaterial": "assets/images/specify/datamodel/borrow_material.png",
			"borrowreturnmaterial": "assets/images/specify/datamodel/borrow_return_material.png",
			"collectingevent": "assets/images/specify/datamodel/collecting_event.png",
			"ce_restore": "assets/images/specify/datamodel/collecting_event.png",
			"collectinginformation": "assets/images/specify/datamodel/collecting_information.png",
			"collectingtrip": "assets/images/specify/datamodel/collection_trip.png",
			"collection": "assets/images/specify/datamodel/collection.png",
			"collectionname": "assets/images/specify/datamodel/collection.png",
			"collectionrelationship": "assets/images/specify/datamodel/collection_relationship.png",
			"collectionreltype": "assets/images/specify/datamodel/collection_rel_type.png",
			"collector": "assets/images/specify/datamodel/collector.png",
			"collectionobject": "assets/images/specify/datamodel/collection_object.png",
			"collectionobjectcitation": "assets/images/specify/datamodel/citation.png",
			"commonnametx": "assets/images/specify/datamodel/common_name.png",
			"commonnametxcitation": "assets/images/specify/datamodel/common_name_taxon_citation.png",
			"container": "assets/images/specify/datamodel/container.png",
			"conservator": "assets/images/specify/datamodel/conservator.png",
			"conservdescription": "assets/images/specify/datamodel/conserv_description.png",
			"conservevent": "assets/images/specify/datamodel/conserv_event.png",
			"datatype": "assets/images/specify/datamodel/data_type.png",
			"determination": "assets/images/specify/datamodel/determination.png",
			"discipline": "assets/images/specify/datamodel/discipline.png",
			"division": "assets/images/specify/datamodel/division.png",
			"dnasequence": "assets/images/specify/datamodel/dna.png",
			"dnasequencingrun": "assets/images/specify/datamodel/dna_seq_run.png",
			"exsiccata": "assets/images/specify/datamodel/exsiccata.png",
			"exsiccataitem": "assets/images/specify/datamodel/exsiccata_item.png",
			"exchangein": "assets/images/specify/datamodel/exchange_in.png",
			"exchangeinprep": "assets/images/specify/datamodel/exchange_in.png",
			"exchangeout": "assets/images/specify/datamodel/exchange_out.png",
			"exchangeoutprep": "assets/images/specify/datamodel/exchange_out.png",
			"fieldnotebook": "assets/images/specify/datamodel/field_notebook.png",
			"fieldnotebookpage": "assets/images/specify/datamodel/field_notebook_page.png",
			"fieldnotebookpageset": "assets/images/specify/datamodel/field_notebook_page_set.png",
			"fundingagent": "assets/images/specify/datamodel/fundingagent.png",
			"geocoorddetail": "assets/images/specify/datamodel/geo_coord_detail.png",
			"geography": "assets/images/specify/datamodel/geography.png",
			"gift": "assets/images/specify/datamodel/gift.png",
			"geologictimeperiod": "assets/images/specify/datamodel/chronostratigraphy.png",
			"inforequest": "assets/images/specify/datamodel/information_request.png",
			"institution": "assets/images/specify/datamodel/institution.png",
			"institutionnetwork": "assets/images/specify/datamodel/inst_network.png",
			"journal": "assets/images/specify/datamodel/journal.png",
			"lithostrat": "assets/images/specify/datamodel/stratigraphy.png",
			"loan": "assets/images/specify/datamodel/loan.png",
			"loanreturnpreparation": "assets/images/specify/datamodel/loan_return_prep.png",
			"locality": "assets/images/specify/datamodel/locality.png",
			"localitydetail": "assets/images/specify/datamodel/locality_detail.png",
			"localitynamealias": "assets/images/specify/datamodel/locality_name_alias.png",
			"otheridentifier": "assets/images/specify/datamodel/other_identifier.png",
			"paleocontext": "assets/images/specify/datamodel/paleocontext.png",
			"permit": "assets/images/specify/datamodel/permit.png",
			"preparation": "assets/images/specify/datamodel/preparation.png",
			"preptype": "assets/images/specify/datamodel/prep_type.png",
			"picklist": "assets/images/specify/datamodel/pick_list.png",
			"project": "assets/images/specify/datamodel/project.png",
			"referencework": "assets/images/specify/datamodel/reference_work.png",
			"repositoryagreement": "assets/images/specify/datamodel/repository_agreement.png",
			"shipment": "assets/images/specify/datamodel/shipment.png",
			"storage": "assets/images/specify/datamodel/storage.png",
			"taxon": "assets/images/specify/datamodel/taxon.png",
			"treatmentevent": "assets/images/specify/datamodel/treatment_event.png",
			"collectionobjectattribute": "assets/images/specify/datamodel/collection_object_attr.png",
			"collectingeventattribute": "assets/images/specify/datamodel/collecting_event_attr.png",
			"preparationattribute": "assets/images/specify/datamodel/preparation_attr.png",
			"accessionattachment": "assets/images/specify/datamodel/accession_attachment.png",
			"agentattachment": "assets/images/specify/datamodel/agent_attachment.png",
			"borrowattachment": "assets/images/specify/datamodel/borrow_attachment.png",
			"collectingeventattachment": "assets/images/specify/datamodel/collecting_event_attachment.png",
			"collectionobjectattachment": "assets/images/specify/datamodel/collection_object_attachment.png",
			"conservdescriptionattachment": "assets/images/specify/datamodel/conserv_description_attachment.png",
			"conserveventattachment": "assets/images/specify/datamodel/conserv_event_attachment.png",
			"dnasequenceattachment": "assets/images/specify/datamodel/dna_attachment.png",
			"dnasequencingrunattachment": "assets/images/specify/datamodel/dna_seq_run_attachment.png",
			"fieldnotebookattachment": "assets/images/specify/datamodel/field_notebook_attachment.png",
			"fieldnotebookpageattachment": "assets/images/specify/datamodel/field_notebook_page_attachment.png",
			"fieldnotebookpagesetattachment": "assets/images/specify/datamodel/field_notebook_page_set_attachment.png",
			"giftattachment": "assets/images/specify/datamodel/gift_attachment.png",
			"loanattachment": "assets/images/specify/datamodel/loan_attachment.png",
			"localityattachment": "assets/images/specify/datamodel/locality_attachment.png",
			"permitattachment": "assets/images/specify/datamodel/permit_attachment.png",
			"preparationattachment": "assets/images/specify/datamodel/preparation_attachment.png",
			"referenceworkattachment": "assets/images/specify/datamodel/refwork_attachment.png",
			"repositoryagreementattachment": "assets/images/specify/datamodel/repository_agreement_attachment.png",
			"storageattachment": "assets/images/specify/datamodel/storage_attachment.png",
			"taxonattachment": "assets/images/specify/datamodel/taxon_attachment.png",
			"group": "assets/images/specify/datamodel/group.png",
			"person": "assets/images/specify/datamodel/person.png",
			"add-person": "assets/images/specify/datamodel/add-person.png",
			"addext-person": "assets/images/specify/datamodel/addext-person.png",
			"del-person": "assets/images/specify/datamodel/del-person.png",
			"rmv-person": "assets/images/specify/datamodel/rmv-person.png",
			"add-group": "assets/images/specify/datamodel/add-group.png",
			"admingroup": "assets/images/specify/datamodel/admingroup.png",
			"admininst": "assets/images/specify/datamodel/admininstitution.png",
			"citation": "assets/images/specify/datamodel/citation.png",
			"instbldg": "assets/images/specify/datamodel/institution_bldg.png",
			"borrowagent": "assets/images/specify/datamodel/agent.png",
			"giftagent": "assets/images/specify/datamodel/agent.png",
			"loanagent": "assets/images/specify/datamodel/agent.png",
			"groupperson": "assets/images/specify/datamodel/agent.png",
			"deaccessionagent": "assets/images/specify/datamodel/agent.png",
			"accessionauthorization": "assets/images/specify/datamodel/permit.png",
			"attachmentmetadata": "assets/images/specify/datamodel/attachment.png",
			"attachmenttag": "assets/images/specify/datamodel/attachment.png",
			"loanpreparation": "assets/images/specify/datamodel/preparation.png",
			"giftpreparation": "assets/images/specify/datamodel/preparation.png",
			"deaccessionpreparation": "assets/images/specify/datamodel/preparation.png",
			"determinationcitation": "assets/images/specify/datamodel/citation.png",
			"localitycitation": "assets/images/specify/datamodel/citation.png",
			"taxoncitation": "assets/images/specify/datamodel/citation.png",
			"determinationcitaton": "assets/images/specify/datamodel/citation.png",
			"collectingeventattr": "assets/images/specify/datamodel/collecting_event_attr.png",
			"preparationattr": "assets/images/specify/datamodel/preparation_attr.png",
			"collectionobjectattr": "assets/images/specify/datamodel/collection_object_attr.png",
			"accession agent": "assets/images/specify/datamodel/agent.png",
			"collecting event": "assets/images/specify/datamodel/collecting_event.png",
			"collecting trip": "assets/images/specify/datamodel/collection_trip.png",
			"collection object": "assets/images/specify/datamodel/collection_object.png",
			"collection object attribute": "assets/images/specify/datamodel/attribute.png",
			"collecting event attribute": "assets/images/specify/datamodel/attribute.png",
			"preparation attribute": "assets/images/specify/datamodel/attribute.png",
			"preparation type": "assets/images/specify/datamodel/prep_type.png",
			"repository agreement": "assets/images/specify/datamodel/repository_agreement.png",
			"reference work": "assets/images/specify/datamodel/reference_work.png",
			"colobjattributes": "assets/images/specify/datamodel/attribute.png",
			"taxontreedef": "assets/images/specify/datamodel/taxon.png",
			"geographytreedef": "assets/images/specify/datamodel/geography.png",
			"geologictimeperiodtreedef": "assets/images/specify/datamodel/chronostratigraphy.png",
			"storagetreedef": "assets/images/specify/datamodel/storage.png",
			"lithostrattreedef": "assets/images/specify/datamodel/stratigraphy.png",
			"taxontree": "assets/images/specify/datamodel/taxon.png",
			"geographytree": "assets/images/specify/datamodel/geography.png",
			"geotimeperiodtree": "assets/images/specify/datamodel/chronostratigraphy.png",
			"storagetree": "assets/images/specify/datamodel/storage.png",
			"lithostrattree": "assets/images/specify/datamodel/stratigraphy.png",
			"treedefeditor": "assets/images/specify/datamodel/taxon.png",
			"treeviewer": "assets/images/specify/datamodel/taxon.png",
			"people": "assets/images/specify/datamodel/group.png"
		};

		this.groups.discipline = {
			"bird": "assets/images/specify/discipline/bird.png",
			"bug": "assets/images/specify/discipline/bug.png",
			"fish": "assets/images/specify/discipline/fish.png",
			"frogs": "assets/images/specify/discipline/frog.png",
			"invertpaleo": "assets/images/specify/discipline/paleo_invert.png",
			"lizard": "assets/images/specify/discipline/lizard.png",
			"lowerplants": "assets/images/specify/discipline/lower_plant.png",
			"mammal": "assets/images/specify/discipline/mammal.png",
			"paleobotany": "assets/images/specify/discipline/paleo_bot.png",
			"plants": "assets/images/specify/discipline/flower.png",
			"snake": "assets/images/specify/discipline/snake.png",
			"spider": "assets/images/specify/discipline/spider.png",
			"vertpaleo": "assets/images/specify/discipline/paleo_vert.png",
			"invertebrate": "assets/images/specify/discipline/starfish.png",
			"vascularplants": "assets/images/specify/discipline/flower.png",
			"herpetology": "assets/images/specify/discipline/frog.png",
			"insect": "assets/images/specify/discipline/bug.png",
			"botany": "assets/images/specify/discipline/flower.png",
			"vascplant": "assets/images/specify/discipline/flower.png",
			"fungi": "assets/images/specify/discipline/lower_plant.png"
		};

		this.groups.imgproc = {
			"ip_camera": "assets/images/specify/imgproc/camera.png",
			"ip_metadata": "assets/images/specify/imgproc/metadata.png",
			"ip_barcode": "assets/images/specify/imgproc/barcode.png",
			"ip_barcode20": "assets/images/specify/imgproc/barcode20x20.png",
			"ip_disk": "assets/images/specify/imgproc/disk.png",
			"ip_circle": "assets/images/specify/imgproc/circle.png"
		};
		this.groups.plugin = {
			"fishbase": "assets/images/specify/fblogootw32.png",
			"biogeomancer": "assets/images/specify/biogeomancer20x20.png",
			"biogeomancer32": "assets/images/specify/biogeomancer.png",
			"convertgeoref": "assets/images/specify/LatLong20x20.png",
			"googleearth": "assets/images/specify/GoogleEarth20x20.png",
			"googleearth16": "assets/images/specify/GoogleEarth16x16.png",
			"defaultplacemark": "assets/images/specify/specify32White.png",
			"geolocate": "assets/images/specify/geolocate.png",
			"geolocate20": "assets/images/specify/geolocate20.png",
			"geolocate16": "assets/images/specify/geolocate16.png",
			"worldwind": "assets/images/specify/worldwind32x32.png",
			"sgr": "assets/images/specify/sgr_32.png",
			"sgrgear": "assets/images/specify/system.png",
			"sgrmatchers": "assets/images/specify/matchers_32.png",
			"colorpalette": "assets/images/specify/colorpalette.png",
			"weightings": "assets/images/specify/weightings.png",
			"searchboxmac": "assets/images/specify/SearchBoxMac.gif",
			"searchboxlinux": "assets/images/specify/Search32x32.png",
			"searchtriangle": "assets/images/specify/SearchTriangle.gif",
			"digir": "assets/images/specify/DigirShovel.png",
			"symbiota": "assets/images/specify/symbiota_32.png"
		};
		this.groups.
		default = {
			"mysqlfull": "assets/images/specify/mysql_logo_name.png",
			"appicon": "assets/images/specify/specify32.png",
			"appicone": "assets/images/specify/specify32E.png",
			"appiconm": "assets/images/specify/specify32M.png",
			"specifylargeicon": "assets/images/specify/specify128.png",
			"specifylargeicone": "assets/images/specify/specify128E.png",
			"specifylargeiconm": "assets/images/specify/specify128M.png",
			"specifyconv": "assets/images/specify/specify128Conv.png",
			"specifysecwiz": "assets/images/specify/spsecwizard128.png",
			"specifysecwiz32": "assets/images/specify/spsecwizard32.png",
			"specify16": "assets/images/specify/specify16.png",
			"specifysplash": "assets/images/specify/SpecifyBigSplash.png",
			"specifysplashcache": "assets/images/specify/SpecifyBigSplash.png",
			"wizardicon": "assets/images/specify/spwizard128.png",
			"wizardicone": "assets/images/specify/spwizard128E.png",
			"wizardiconm": "assets/images/specify/spwizard128M.png",
			"databaseicon": "assets/images/specify/spbackup128.png",
			"databaseicone": "assets/images/specify/spbackup128E.png",
			"databaseiconm": "assets/images/specify/spbackup128M.png",
			"spireports": "assets/images/specify/spireport128.png",
			"spireportse": "assets/images/specify/spireport128.png",
			"spbuilder": "assets/images/specify/spbuilder.png",
			"specifywhite32": "assets/images/specify/specify32White.png",
			"specifywhite32e": "assets/images/specify/specify32EWhite.png",
			"specifywhite32m": "assets/images/specify/specify32MWhite.png",
			"help": "assets/images/specify/win_help.png",
			"machelp": "assets/images/specify/MacHelp24x24.png",
			"save": "assets/images/specify/Save32x32.png",
			"import16": "assets/images/specify/ImportData16x16.png",
			"importimages": "assets/images/specify/ImportImages16x16.png",
			"export16": "assets/images/specify/ExportDataSet16x16.png",
			"exportexcel16": "assets/images/specify/ExportExcelTemplate16x16.png",
			"workbench16": "assets/images/specify/Workbench32x32.png",
			"workbench": "assets/images/specify/Workbench32x32.png",
			"interactions": "assets/images/specify/interactions.png",
			"statistics": "assets/images/specify/Statistics32x32.png",
			"pie_chart": "assets/images/specify/PieChart32x32.png",
			"bar_chart": "assets/images/specify/BarGraph32x32.png",
			"record_set": "assets/images/specify/RecordSet32x32.png",
			"query": "assets/images/specify/Query32x32.png",
			"moretables": "assets/images/specify/more_tables.png",
			"moreforms": "assets/images/specify/more_forms.png",
			"search": "assets/images/specify/Search32x32.png",
			"searchadd": "assets/images/specify/SearchAdd32x32.png",
			"globalsearch": "assets/images/specify/global_search16x16.png",
			"systemsetup": "assets/images/specify/System32x32.png",
			"placeholder": "assets/images/specify/specify32faded.png",
			"lifemapper": "assets/images/specify/lifemapper32.png",
			"ipadexporttask": "assets/images/specify/iPadExportTask.png",
			"labels16": "assets/images/specify/Label16x16.png",
			"reports": "assets/images/specify/Reports32x32.png",
			"reports16": "assets/images/specify/Reports16x16.png",
			"dataset": "assets/images/specify/DataSet32x32.png",
			"dataset16": "assets/images/specify/DataSet16x16.png",
			"trash": "assets/images/specify/trash.png",
			"trashfull": "assets/images/specify/trash_full.png",
			"newdataset": "assets/images/specify/NewDataSet16x16.png",
			"labels": "assets/images/specify/Label32x32.png",
			"form": "assets/images/specify/Form32x32.png",
			"formedit": "assets/images/specify/FormEdit32x32.png",
			"editform20": "assets/images/specify/FormEdit20x20.png",
			"editicon": "assets/images/specify/edit_icon.gif",
			"editform": "assets/images/specify/FormEdit16x16.png",
			"infoicon": "assets/images/specify/info.png",
			"metadata": "assets/images/specify/metadata.png",
			"filter20": "assets/images/specify/filter20x20.png",
			"reload": "assets/images/specify/reload.png",
			"viewform16": "assets/images/specify/Form16x16.png",
			"viewform": "assets/images/specify/Form32x32.png",
			"cleanup": "assets/images/specify/cleanup.png",
			"loading": "assets/images/specify/loading.png",
			"data_entry": "assets/images/specify/Data_Entry.png",
			"configure16": "assets/images/specify/Configure16x16.png",
			"carryforward": "assets/images/specify/CarryForward16x16.png",
			"carryforward20x20": "assets/images/specify/CarryForward20x20.png",
			"email": "assets/images/specify/Email32x32.png",
			"taskbar": "assets/images/specify/taskbar.png",
			"configure": "assets/images/specify/Configure20x20.png",
			"addrec": "assets/images/specify/AddNewRecord20x20.png",
			"delrec": "assets/images/specify/RemoveRecord20x20.png",
			"addrecord": "assets/images/specify/AddNewRecord32x32.png",
			"delrecord": "assets/images/specify/RemoveRecord16x16.png",
			"spreadsheet20": "assets/images/specify/Grid20x20.png",
			"spreadsheet16": "assets/images/specify/Grid16x16.png",
			"spreadsheet": "assets/images/specify/Grid32x32.png",
			"spreadsheetedit": "assets/images/specify/GridEdit32x32.png",
			"export": "assets/images/specify/ExportDataSet20x20.png",
			"upload": "assets/images/specify/upload_workbench20x20.png",
			"validatewb": "assets/images/specify/validate_workbench20x20.png",
			"eraser": "assets/images/specify/Clear20x20.png",
			"eraser16": "assets/images/specify/Clear16x16.png",
			"cardimage": "assets/images/specify/ImageWindow20x20.png",
			"localitymapper": "assets/images/specify/map20x20.png",
			"mapicon": "assets/images/specify/map.png",
			"controledit": "assets/images/specify/EditProperties20x20.png",
			"editprops": "assets/images/specify/EditProperties32x32.png",
			"plugins": "assets/images/specify/plug_in.png",
			"dropindicator": "assets/images/specify/dropindicator.png",
			"formatting": "assets/images/specify/formatting.png",
			"weblink": "assets/images/specify/weblink.png",
			"calendar": "assets/images/specify/Calendar32x32.png",
			"visualquery": "assets/images/specify/Search32x32.png",
			"imagewindow": "assets/images/specify/ImageWindow20x20.png",
			"zoomin20": "assets/images/specify/ZoomIn20x20.png",
			"zoomout20": "assets/images/specify/ZoomOut20x20.png",
			"userinterface": "assets/images/specify/FormEdit32x32.png",
			"dropdownarrow": "assets/images/specify/dropdownarrow.gif",
			"uparrow": "assets/images/specify/up.png",
			"downarrow": "assets/images/specify/down.png",
			"blankicon": "assets/images/specify/blank32x32.png",
			"plussign": "assets/images/specify/add.png",
			"minussign": "assets/images/specify/delete.png",
			"graydot": "assets/images/specify/graydot.gif",
			"separator": "assets/images/specify/separator16.gif",
			"key": "assets/images/specify/key.png",
			"cloneobj": "assets/images/specify/clone.png",
			"relatedtable": "assets/images/specify/related_table.png",
			"tablefield": "assets/images/specify/field.png",
			"webpage": "assets/images/specify/html.png",
			"brokenimage": "assets/images/specify/gtk-brokenimage.png",
			"firstrec": "assets/images/specify/first.gif",
			"prevrec": "assets/images/specify/prev.gif",
			"nextrec": "assets/images/specify/next.gif",
			"lastrec": "assets/images/specify/last.gif",
			"close": "assets/images/specify/close.png",
			"closehover": "assets/images/specify/close_hover.png",
			"print": "assets/images/specify/printer.png",
			"backup": "assets/images/specify/backup.png",
			"clipboardcopy": "assets/images/specify/clipboardPaste32.png",
			"clipboardpaste": "assets/images/specify/clipboardPaste32.png",
			"validationvalid": "assets/images/specify/validation-valid.gif",
			"validationwarning": "assets/images/specify/FeedbackYellow32x32.png",
			"validationerror": "assets/images/specify/FeedbackRed32x32.png",
			"green arrow down": "assets/images/specify/green_arrow_down.gif",
			"green arrow up": "assets/images/specify/green_arrow_up.gif",
			"linked": "assets/images/specify/linked.png",
			"linkedright": "assets/images/specify/linked_right.png",
			"down": "assets/images/specify/Down16x16.png",
			"forward": "assets/images/specify/Forward16x16.png",
			"wbvalidatordown": "assets/images/specify/down_32.png",
			"wbvalidatorup": "assets/images/specify/up_32.png",
			"exclaimgreen": "assets/images/specify/exclaim_green.gif",
			"exclaimyellow": "assets/images/specify/exclaim_yellow.gif",
			"exclaimred": "assets/images/specify/exclaim.gif",
			"multikid": "assets/images/specify/MultiKid.png",
			"singlekid": "assets/images/specify/SingleKid.png",
			"minimize": "assets/images/specify/minimize.gif",
			"maximize": "assets/images/specify/maximize.gif",
			"map": "assets/images/specify/Map16x16.png",
			"unmap": "assets/images/specify/Unmap16x16.png",
			"reorderup": "assets/images/specify/ReorderUp16x16.png",
			"reorderdown": "assets/images/specify/ReorderDown16x16.png",
			"checkmark": "assets/images/specify/Checkmark32x32.png",
			"attach": "assets/images/specify/attachicon.png",
			"attach16": "assets/images/specify/attachicon16.png",
			"reddot6x6": "assets/images/specify/reddot.gif",
			"isoicon": "assets/images/specify/iso.png",
			"preferences": "assets/images/specify/preferences.png",
			"attachmentprefs": "assets/images/specify/attach_pref.png",
			"ttv_subtree": "assets/images/specify/ExpandChildren32x32.png",
			"ttv_wholetree": "assets/images/specify/ExpandParent32x32.png",
			"ttv_alldescend": "assets/images/specify/expand.png",
			"ttv_syncviews": "assets/images/specify/sync.png",
			"ttv_toparent": "assets/images/specify/undo.png",
			"ttv_splitviewmode": "assets/images/specify/SplitWindow32x32.png",
			"ttv_singleviewmode": "assets/images/specify/SingleView32x32.png",
			"audio": "assets/images/specify/audio.png",
			"video": "assets/images/specify/Video32x32.png",
			"image": "assets/images/specify/Image-Window-B-32x32.png",
			"unknown": "assets/images/specify/binary.png",
			"text": "assets/images/specify/text.png",
			"pdf": "assets/images/specify/pdf.png",
			"html": "assets/images/specify/html.png",
			"msexcel": "assets/images/specify/msexcel64x64.png",
			"msword": "assets/images/specify/msword64x64.png",
			"mspowerpoint": "assets/images/specify/msppt64x64.png",
			"move_to_start": "assets/images/specify/start.png",
			"move_left": "assets/images/specify/1leftarrow.png",
			"move_right": "assets/images/specify/1rightarrow.png",
			"move_to_end": "assets/images/specify/finish.png",
			"skeleton": "assets/images/specify/fishskel.png",
			"xray": "assets/images/specify/xray.png",
			"etoh": "assets/images/specify/fishinjar.png",
			"cs": "assets/images/specify/fishskeljar.png",
			"latlonpoint": "assets/images/specify/LatLonPoint32x32.png",
			"latlonline": "assets/images/specify/LatLonLine32x32.png",
			"latlonrect": "assets/images/specify/LatLonRect32x32.png",
			"latlonlineleft": "assets/images/specify/LatLonLineLeft32x32.png",
			"latlonlineright": "assets/images/specify/LatLonLineRight32x32.png",
			"latlonrecttopleft": "assets/images/specify/LatLonRectLeft32x32.png",
			"latlonrectbottomright": "assets/images/specify/LatLonRectRight32x32.png",
			"latlonpointsel": "assets/images/specify/LatLonPoint32x32Sel.png",
			"latlonlinesel": "assets/images/specify/LatLonLine32x32Sel.png",
			"latlonrectsel": "assets/images/specify/LatLonRect32x32Sel.png",
			"top": "assets/images/specify/RightSideUp.png",
			"bottom": "assets/images/specify/LeftSideDown.png",
			"both": "assets/images/specify/UpAndDown.png",
			"miscpref": "assets/images/specify/Miscellaneous32x32.png",
			"treepref": "assets/images/specify/Tree32x32.png",
			"security": "assets/images/specify/security.png",
			"securityon": "assets/images/specify/security_on.png",
			"securityoff": "assets/images/specify/security_off.png",
			"login": "assets/images/specify/login.png",
			"mysql": "assets/images/specify/mysql_logo.png",
			"folder": "assets/images/specify/folder32x32.png",
			"sheet": "assets/images/specify/sheet32x32.png",
			"plantspecimen": "assets/images/specify/plantspec32x32.png",
			"splicer": "assets/images/specify/data_split.png",
			"morphbanklogo": "assets/images/specify/mbLogoHeader.png",
			"exportspmobile": "assets/images/specify/export_spmobile.png",
			"specifysmallipad128x128": "assets/images/specify/SpecifySmalliPad128x128.png",
			"showmap": "assets/images/specify/map20x20.png",
			"recordset": "assets/images/specify/RecordSet32x32.png",
			"startup": "assets/images/specify/specify32.png",
			"newrecord": "assets/images/specify/add.png",
			"deleterecord": "assets/images/specify/delete.png",
			"createobj": "assets/images/specify/add.png",
			"warning": "assets/images/specify/FeedbackYellow32x32.png",
			"error": "assets/images/specify/FeedbackRed32x32.png",
			"ttv_newchild": "assets/images/specify/add.png",
			"ttv_editnode": "assets/images/specify/edit_icon.gif",
			"ttv_delnode": "assets/images/specify/delete.png"
		};
	});
