'use strict';

angular.module('specifyDataCleanerApp')
	.service('Icons', function() {
		// AngularJS will instantiate a singleton by calling "new" on this function
		{
			"colobj_backstop": "assets/images/specify/datamodel/collection_object.png",
			"accession": "assets/images/specify/datamodel/accession.png",
			"deaccession": "assets/images/specify/datamodel/deaccession.png",
			"appraisal": "assets/images/specify/datamodel/appraisal.png",
			"accessionagent": "assets/images/specify/datamodel/agent.png",
			"address": "assets/images/specify/datamodel/address.png",
			"addressofrecord": "assets/images/specify/datamodel/address.png",
			"agent": "assets/images/specify/datamodel/agent.png",
			"agentgeography": "assets/images/specify/datamodel/agent_geography.png",
			"agentspecialty": "assets/images/specify/datamodel/agent_specialty.png",
			"agentvariant": "assets/images/specify/datamodel/agent.png",
			"author": "assets/images/specify/datamodel/author.png",
			"attachment": "assets/images/specify/datamodel/attachment.png",
			"attribute": "assets/images/specify/datamodel/attribute.png",
			"attributedef": "assets/images/specify/datamodel/attribute_def.png",
			"borrow": "assets/images/specify/datamodel/borrow.png",
			"borrowmaterial": "assets/images/specify/datamodel/borrow_material.png",
			"borrowreturnmaterial": "assets/images/specify/datamodel/borrow_return_material.png",
			"collectingevent": "assets/images/specify/datamodel/collecting_event.png",
			"ce_restore": "assets/images/specify/datamodel/collecting_event.png",
			"collectinginformation": "assets/images/specify/datamodel/collecting_information.png",
			"collectingtrip": "assets/images/specify/datamodel/collection_trip.png",
			"collection": "assets/images/specify/datamodel/collection.png",
			"collectionname": "assets/images/specify/datamodel/collection.png",
			"collectionrelationship": "assets/images/specify/datamodel/collection_relationship.png",
			"collectionreltype": "assets/images/specify/datamodel/collection_rel_type.png",
			"collector": "assets/images/specify/datamodel/collector.png",
			"collectionobject": "assets/images/specify/datamodel/collection_object.png",
			"collectionobjectcitation": "assets/images/specify/datamodel/citation.png",
			"commonnametx": "assets/images/specify/datamodel/common_name.png",
			"commonnametxcitation": "assets/images/specify/datamodel/common_name_taxon_citation.png",
			"container": "assets/images/specify/datamodel/container.png",
			"conservator": "assets/images/specify/datamodel/conservator.png",
			"conservdescription": "assets/images/specify/datamodel/conserv_description.png",
			"conservevent": "assets/images/specify/datamodel/conserv_event.png",
			"datatype": "assets/images/specify/datamodel/data_type.png",
			"determination": "assets/images/specify/datamodel/determination.png",
			"discipline": "assets/images/specify/datamodel/discipline.png",
			"division": "assets/images/specify/datamodel/division.png",
			"dnasequence": "assets/images/specify/datamodel/dna.png",
			"dnasequencingrun": "assets/images/specify/datamodel/dna_seq_run.png",
			"exsiccata": "assets/images/specify/datamodel/exsiccata.png",
			"exsiccataitem": "assets/images/specify/datamodel/exsiccata_item.png",
			"exchangein": "assets/images/specify/datamodel/exchange_in.png",
			"exchangeinprep": "assets/images/specify/datamodel/exchange_in.png",
			"exchangeout": "assets/images/specify/datamodel/exchange_out.png",
			"exchangeoutprep": "assets/images/specify/datamodel/exchange_out.png",
			"fieldnotebook": "assets/images/specify/datamodel/field_notebook.png",
			"fieldnotebookpage": "assets/images/specify/datamodel/field_notebook_page.png",
			"fieldnotebookpageset": "assets/images/specify/datamodel/field_notebook_page_set.png",
			"fundingagent": "assets/images/specify/datamodel/fundingagent.png",
			"geocoorddetail": "assets/images/specify/datamodel/geo_coord_detail.png",
			"geography": "assets/images/specify/datamodel/geography.png",
			"gift": "assets/images/specify/datamodel/gift.png",
			"geologictimeperiod": "assets/images/specify/datamodel/chronostratigraphy.png",
			"inforequest": "assets/images/specify/datamodel/information_request.png",
			"institution": "assets/images/specify/datamodel/institution.png",
			"institutionnetwork": "assets/images/specify/datamodel/inst_network.png",
			"journal": "assets/images/specify/datamodel/journal.png",
			"lithostrat": "assets/images/specify/datamodel/stratigraphy.png",
			"loan": "assets/images/specify/datamodel/loan.png",
			"loanreturnpreparation": "assets/images/specify/datamodel/loan_return_prep.png",
			"locality": "assets/images/specify/datamodel/locality.png",
			"localitydetail": "assets/images/specify/datamodel/locality_detail.png",
			"localitynamealias": "assets/images/specify/datamodel/locality_name_alias.png",
			"otheridentifier": "assets/images/specify/datamodel/other_identifier.png",
			"paleocontext": "assets/images/specify/datamodel/paleocontext.png",
			"permit": "assets/images/specify/datamodel/permit.png",
			"preparation": "assets/images/specify/datamodel/preparation.png",
			"preptype": "assets/images/specify/datamodel/prep_type.png",
			"picklist": "assets/images/specify/datamodel/pick_list.png",
			"project": "assets/images/specify/datamodel/project.png",
			"referencework": "assets/images/specify/datamodel/reference_work.png",
			"repositoryagreement": "assets/images/specify/datamodel/repository_agreement.png",
			"shipment": "assets/images/specify/datamodel/shipment.png",
			"storage": "assets/images/specify/datamodel/storage.png",
			"taxon": "assets/images/specify/datamodel/taxon.png",
			"treatmentevent": "assets/images/specify/datamodel/treatment_event.png",
			"collectionobjectattribute": "assets/images/specify/datamodel/collection_object_attr.png",
			"collectingeventattribute": "assets/images/specify/datamodel/collecting_event_attr.png",
			"preparationattribute": "assets/images/specify/datamodel/preparation_attr.png",
			"accessionattachment": "assets/images/specify/datamodel/accession_attachment.png",
			"agentattachment": "assets/images/specify/datamodel/agent_attachment.png",
			"borrowattachment": "assets/images/specify/datamodel/borrow_attachment.png",
			"collectingeventattachment": "assets/images/specify/datamodel/collecting_event_attachment.png",
			"collectionobjectattachment": "assets/images/specify/datamodel/collection_object_attachment.png",
			"conservdescriptionattachment": "assets/images/specify/datamodel/conserv_description_attachment.png",
			"conserveventattachment": "assets/images/specify/datamodel/conserv_event_attachment.png",
			"dnasequenceattachment": "assets/images/specify/datamodel/dna_attachment.png",
			"dnasequencingrunattachment": "assets/images/specify/datamodel/dna_seq_run_attachment.png",
			"fieldnotebookattachment": "assets/images/specify/datamodel/field_notebook_attachment.png",
			"fieldnotebookpageattachment": "assets/images/specify/datamodel/field_notebook_page_attachment.png",
			"fieldnotebookpagesetattachment": "assets/images/specify/datamodel/field_notebook_page_set_attachment.png",
			"giftattachment": "assets/images/specify/datamodel/gift_attachment.png",
			"loanattachment": "assets/images/specify/datamodel/loan_attachment.png",
			"localityattachment": "assets/images/specify/datamodel/locality_attachment.png",
			"permitattachment": "assets/images/specify/datamodel/permit_attachment.png",
			"preparationattachment": "assets/images/specify/datamodel/preparation_attachment.png",
			"referenceworkattachment": "assets/images/specify/datamodel/refwork_attachment.png",
			"repositoryagreementattachment": "assets/images/specify/datamodel/repository_agreement_attachment.png",
			"storageattachment": "assets/images/specify/datamodel/storage_attachment.png",
			"taxonattachment": "assets/images/specify/datamodel/taxon_attachment.png",
			"group": "assets/images/specify/datamodel/group.png",
			"person": "assets/images/specify/datamodel/person.png",
			"add-person": "assets/images/specify/datamodel/add-person.png",
			"addext-person": "assets/images/specify/datamodel/addext-person.png",
			"del-person": "assets/images/specify/datamodel/del-person.png",
			"rmv-person": "assets/images/specify/datamodel/rmv-person.png",
			"add-group": "assets/images/specify/datamodel/add-group.png",
			"admingroup": "assets/images/specify/datamodel/admingroup.png",
			"admininst": "assets/images/specify/datamodel/admininstitution.png",
			"citation": "assets/images/specify/datamodel/citation.png",
			"instbldg": "assets/images/specify/datamodel/institution_bldg.png",
			"borrowagent": "assets/images/specify/datamodel/agent.png",
			"giftagent": "assets/images/specify/datamodel/agent.png",
			"loanagent": "assets/images/specify/datamodel/agent.png",
			"groupperson": "assets/images/specify/datamodel/agent.png",
			"deaccessionagent": "assets/images/specify/datamodel/agent.png",
			"accessionauthorization": "assets/images/specify/datamodel/permit.png",
			"attachmentmetadata": "assets/images/specify/datamodel/attachment.png",
			"attachmenttag": "assets/images/specify/datamodel/attachment.png",
			"loanpreparation": "assets/images/specify/datamodel/preparation.png",
			"giftpreparation": "assets/images/specify/datamodel/preparation.png",
			"deaccessionpreparation": "assets/images/specify/datamodel/preparation.png",
			"determinationcitation": "assets/images/specify/datamodel/citation.png",
			"localitycitation": "assets/images/specify/datamodel/citation.png",
			"taxoncitation": "assets/images/specify/datamodel/citation.png",
			"determinationcitaton": "assets/images/specify/datamodel/citation.png",
			"collectingeventattr": "assets/images/specify/datamodel/collecting_event_attr.png",
			"preparationattr": "assets/images/specify/datamodel/preparation_attr.png",
			"collectionobjectattr": "assets/images/specify/datamodel/collection_object_attr.png",
			"accession agent": "assets/images/specify/datamodel/agent.png",
			"collecting event": "assets/images/specify/datamodel/collecting_event.png",
			"collecting trip": "assets/images/specify/datamodel/collection_trip.png",
			"collection object": "assets/images/specify/datamodel/collection_object.png",
			"collection object attribute": "assets/images/specify/datamodel/attribute.png",
			"collecting event attribute": "assets/images/specify/datamodel/attribute.png",
			"preparation attribute": "assets/images/specify/datamodel/attribute.png",
			"preparation type": "assets/images/specify/datamodel/prep_type.png",
			"repository agreement": "assets/images/specify/datamodel/repository_agreement.png",
			"reference work": "assets/images/specify/datamodel/reference_work.png",
			"colobjattributes": "assets/images/specify/datamodel/attribute.png",
			"taxontreedef": "assets/images/specify/datamodel/taxon.png",
			"geographytreedef": "assets/images/specify/datamodel/geography.png",
			"geologictimeperiodtreedef": "assets/images/specify/datamodel/chronostratigraphy.png",
			"storagetreedef": "assets/images/specify/datamodel/storage.png",
			"lithostrattreedef": "assets/images/specify/datamodel/stratigraphy.png",
			"taxontree": "assets/images/specify/datamodel/taxon.png",
			"geographytree": "assets/images/specify/datamodel/geography.png",
			"geotimeperiodtree": "assets/images/specify/datamodel/chronostratigraphy.png",
			"storagetree": "assets/images/specify/datamodel/storage.png",
			"lithostrattree": "assets/images/specify/datamodel/stratigraphy.png",
			"treedefeditor": "assets/images/specify/datamodel/taxon.png",
			"treeviewer": "assets/images/specify/datamodel/taxon.png",
			"people": "assets/images/specify/datamodel/group.png"
		};
	});
